version: '3.6'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: nisq
      POSTGRES_USER: nisq
      POSTGRES_DB: nisq
  nisq-analyzer:
    image: planqk/nisq-analyzer
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: nisq
      POSTGRES_PASSWORD: nisq
      POSTGRES_DB: nisq
      NISQ_HOSTNAME: qiskit-service
      NISQ_PORT: 5000
      NISQ_VERSION: v1.0
    ports:
      - '8081:8080'
    networks:
      - default
networks:
  default:
    driver: bridge
