version: '3.6'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: nisq
      POSTGRES_USER: nisq
      POSTGRES_DB: nisq
    command: -p 5060
    ports:
      - "5060:5060"
  nisq-analyzer:
    image: planqk/nisq-analyzer
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5060
      POSTGRES_USER: nisq
      POSTGRES_PASSWORD: nisq
      POSTGRES_DB: nisq
      NISQ_HOSTNAME: qiskit-service
      NISQ_PORT: 5013
      NISQ_VERSION: v1.0
    ports:
      - '5010:5010'
    networks:
      - default
networks:
  default:
    driver: bridge
